### ISSUE TITLE
Uncaught TypeError: e.props.onGridSort is not a function

### ISSUE THREAD

**Issue by omarefg** [plangrid/react-file-viewer#110]
When I render a CSV or XLSX file, if I click on a column Header the application break. 

Submitting a pull request with a possible fix.

**Comment by MohsinGhani** [comment]
Is there any fix available for this issue?

**Comment by anguof** [comment]
> Is there any fix available for this issue?

You can set the css attribute value of point-events to none.

**Comment by anguof** [comment]
> Is there any fix available for this issue?

You can set the css attribute value of point-events to none.

**Comment by bahimzabir** [comment]
In your global css file add that:
```
.react-grid-HeaderCell-sortable {
  cursor: none !important;
  pointer-events: none !important;
}
```
change `react-grid-HeaderCell-sortable` to whatever the class name of the header
