### ISSUE TITLE
csv, xlsx, image can't able to open in full view 

### ISSUE THREAD

**Issue by BalachandarNarayanan** [plangrid/react-file-viewer#141]
![csv_xlsx_image_issue](https://user-images.githubusercontent.com/28632036/75513455-e169ee00-5a2f-11ea-9da0-6c3a40a13667.JPG)

Advise me how to fix this issue

**Comment by BalachandarNarayanan** [comment]
Working fine. Regret for my mistake

**Comment by AravindTReddy** [comment]
Hey Bala, 

I am trying to display .doc, .docx, .pdf, .csv and having issues rendering it.

```
handleFile = event => {
    this.setState({
      file: event.target.files[0]
    });
  };

  importFile = () => {
    const { file } = this.state;
    if(file) {
      this.setState({type: file.type, name: file.name, path: file.path })
    }
    else {
      this.setState({Error:'please choose a .doc/.pdf file and try uploading again'})
    }

  }

<input type="file"
                    id="docpicker"
                    onChange={this.handleFile}
                    accept=".doc,.docx,application/msword, .pdf" />

<FileViewer
                    fileType={this.state.type}
                    filePath={this.state.path}
                    key= {this.state.path}
                    />
```
I always get **.application/pdf is not supported.** when i upload a pdf and **.application/vnd.openxmlformats-officedocument.wordprocessingml.document is not supported.** when i upload a doc and same goes with .csv and other formats

Can you please push me in the right direction. Thanks a lot
Can you please share your snippet

**Comment by zhuzhuxie** [comment]
Hi BalachandarNarayanan ,
   can you tell me how to fix this error?
error:
    csv, xlsx, image can't able to open in full view

**Comment by JonesLiang** [comment]
how to fix it? bro. I need help
