### ISSUE TITLE
e.props.onGridSort 

### ISSUE THREAD

**Issue by kaialsh705** [plangrid/react-file-viewer#205]
When I render XLSX file, if I click on a column Header the application break.
Uncaught TypeError: e.props.onGridSort is not a function
and i pass onGridSort props.
how i fix.

**Comment by TjeneBen** [comment]
same here

**Comment by alikhan866** [comment]
same issue I am also facing

**Comment by janhavi-debug** [comment]
why was this closed? I am still getting this error

**Comment by xiaoshuiya** [comment]
how to resolve?my brother!

**Comment by SlahserZ** [comment]
same problem

**Comment by Jothi-icanio** [comment]
Finally, I sorted this using CSS,

   .react-grid-HeaderCell-sortable {
    cursor: pointer !important;
    pointer-events: none !important;
  }
  
  Do we have any other better option?
