### ISSUE TITLE
Trying to render a docx file getting an Uncaught Error

### ISSUE THREAD

**Issue by sho13** [plangrid/react-file-viewer#42]
I receive an error when I attempt to run a <FileViewer /> component
I have the fileType set to `docx` and the file path is imported, yet it's coming back with this error.

`Uncaught Error: Can't find end of central directory : is this a zip file ? If it is, see http://stuk.github.io/jszip/documentation/howto/read_zip.html`

EDIT:: so after doing some more exploring, i think this is an isolated problem, 

the module works in a separate project. but if anyone can provide some insight it'd be greatly appreciated. 

EDIT2:: 

I also am getting this response when trying to render a `pdf` file.

`Deprecated API usage: getDocument is called with pdfDataRangeTransport, passwordCallback or progressCallback argument`

**Comment by amansani** [comment]
I am facing the same errors, any solutions or inputs are highly appreciated?

**Comment by ZakKa89** [comment]
Same here

**Comment by Koomita** [comment]
Same here
