### ISSUE TITLE
Won't Build with "InvalidCharacterError"

### ISSUE THREAD

**Issue by tjwebb** [plangrid/react-file-viewer#51]
I can run the demo if I clone/build the repo, but I get the following error when including the same component into my own React app.

React: 16
node: 8.4

```
×
InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/file-viewer.28f897ed.jsx') is not a valid name.
```

**Comment by philfontaine** [comment]
Ran into the same issue, seems to be broken as of 0.3.48. 
0.3.47 works fine.

**Comment by ViktoriyaSavkina** [comment]
Thanks for reporting this, we'll look into this shortly.

**Comment by Jawadgee** [comment]
please fix this issue. I need this package to complete my final project or suggest some solution I am using react 15.6. The requirement is to view files in browser.

**Comment by ViktoriyaSavkina** [comment]
@Jawadgee we're looking into this. Please use version 0.3.47 of the library for now

**Comment by Jawadgee** [comment]
@ViktoriyaSavkina thanks.  is it compatible with react 15.6.. . and please show a clear example for this version

**Comment by kevinflo** [comment]
This is so odd, this is the only thread online I can find with a similar error to what I'm seeing in a completely different library https://github.com/wenliangdai/react-audioplayer

For that I'm seeing the same /static/media path and everything `Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/Audio.24501068.jsx') is not a valid name.` Looks like what is supposed to get passed into this in a success case is just "p" or "div" etc.
